### ISSUE TITLE
Consider adding source generator version

### ISSUE THREAD

**Issue by CptWesley** [MarkCiliaVincenti/Backport.System.Threading.Lock#1]
Because locks are usually part of the implementation details and not part of the public API, it would be nice to be able to use this polyfill without bothering the consumers of our libraries with an extra transitive dependency. To that extend I think it would be a nice addition to provide a seperate roslyn source generator package that emits the `Lock` code into the consumers code base as internal classes. This way the code is essentially copied into the consuming libraries code base during compilation and does not create that extra transitive dependency.

Of course this comes with a downside: because the `Lock` type is now internal for anything before `.NET9`, we can't take or return any `Lock` objects in our public API. But as mentioned before, for most cases this doesn't happy anyway.

My proposal would be to make a second project (e.g. `Backport.System.Threading.Lock.SourceGenerator`) in the solution which emits the `Lock` and `LockFactory` code, which can be configured through the `.csproj` to emit the code either as `public` or `internal`. The default should probably be `internal`. The `Backport.System.Threading.Lock` project can add a compile-time reference to `Backport.System.Threading.Lock.SourceGenerator` and configure it to emit the code as `public`. The `Lock` and `LockFactory` code can then be removed from `Backport.System.Threading.Lock` so that the code only lives in a single space.

This would result in 2 packages:
- `Backport.System.Threading.Lock`: exactly the same package it is now (but compiled slightly differently). A runtime dependency with a `public` `Lock` class.
- `Backport.System.Threading.Lock.SourceGenerator`: a compile-time roslyn source code generator package that injects an `internal` `Lock` type to consumers of the library.

If you like this idea, I wouldn't mind having a go at it and creating a pull request for it in the next few days.

**Comment by MarkCiliaVincenti** [comment]
Hi @CptWesley,

That's an interesting idea, however I am not fully convinced it will work because type forwarding and security transparency can only be set at an assembly level.

https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/Properties/AssemblyInfo.cs

But it might work if it's internal instead. Public is risky because if you can't get the type forwarding set you risk someone depending on that library from .NET 8.0 and using System.Threading.Lock transitively, and someone using .NET 9.0 depending on the latter project.

**Comment by CptWesley** [comment]
I don't think either of those attributes are much of a concern when the package is shipped as source generator.

- The `SecurityTransparentAttribute` should then be up to the consumer (since they are now shipping the implementation). And this attribute has no effect in modern .NET (Core) projects anyway.
- No `TypeForwardedToAttribute` means the code will either target the consuming assembly itself or the standard library for the `Lock` type. I can't really think of any situations where this would be problematic.

The suggestion to add a flag to emit the code as public would mostly be there to allow you to use the source generator when compiling the regular, non-source generator package without copy-pasting code. This can of course also be done through explicitly adding the files to the build and using some defined constant macros.

**Comment by MarkCiliaVincenti** [comment]
The TypeForwardedTo is critical.

Let's say you make a LibraryA depending on Backport.System.Threading.Lock and targeting net8 and net9
Someone depends on LibraryA from LibraryB which targets net8 and also uses the backport transitively
Someone depends on LibraryB from LibraryC which targets net9

LibraryA will work, no issues.
But when LibraryC makes a call to LibraryB, it would have transitively used the net9 version of Backport.System.Threading.Lock, and LibraryB will try to use the backport code which is excluded because of this:

﻿#if NET5_0_OR_GREATER && !NET9_0_OR_GREATER
﻿in
https://github.com/MarkCiliaVincenti/Backport.System.Threading.Lock/blob/master/Backport.System.Threading.Lock/Lock.cs

**Comment by MarkCiliaVincenti** [comment]
... but if you make the sourcegenerator create internal classes instead, you block the possibility above because LibraryB would not be able to use Backport.System.Threading.Lock transitively.

**Comment by MarkCiliaVincenti** [comment]
@CptWesley will you be working on a PR for this? It would be greatly appreciated.

**Comment by CptWesley** [comment]
@MarkCiliaVincenti I see how the attribute is necessary when the backport is public. Although I would argue that it would be good practise for `LibraryB` to target the superset of the targets of all its dependencies, that would prevent such dependency hells.

And yes, I will give it a go tomorrow morning

**Comment by MarkCiliaVincenti** [comment]
There's just one situation where it would fail but not sure if there's a way we can prevent it. Suppose you have a solution with multiple projects and you implement the source generator in project A that multi targets net8 and net9 and you have project B that depends on A via NuGet packages but you set InternalsVisibleTo to project B which only targets net8. Now if someone depends on project B with net9 there's going to be a problem.

**Comment by CptWesley** [comment]
The generator could actually emit the `TypeForwardedToAttribute` as well, which should solve the issue (at least it did in my quick local test setup).

**Comment by MarkCiliaVincenti** [comment]
Unfortunately the TypeForwardedTo works at assembly level not at a class level. We can't have that  because otherwise we would be forwarding all classes in the assembly where the source generators runs in.

**Comment by CptWesley** [comment]
It works at an assembly level, but it adds a forwarding rule only for the type passed to the attribute, not for all types in the assembly. The latter would also not make a lot of sense, since you add type forwarding rules for types that your assembly doesn't define.

**Comment by MarkCiliaVincenti** [comment]
> It works at an assembly level, but it adds a forwarding rule only for the type passed to the attribute, not for all types in the assembly. The latter would also not make a lot of sense, since you add type forwarding rules for types that your assembly doesn't define.

Oh cool, I had totally misunderstood this.
